package dev.simplified.persistence.source;

import com.google.gson.annotations.SerializedName;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Java mirror of the {@code skyblock-data/data/v1/index.json} manifest schema.
 *
 * <p>The manifest is emitted by {@code scripts/generate_index.py} in the
 * {@code skyblock-data} repository and regenerated by CI on every pull request. Each
 * entry carries everything a consumer needs to locate the primary JSON file, an optional
 * {@code _extra} companion, and the content hashes used by Phase 4c's delta engine.
 *
 * <p>Deserialization is driven by Gson reflective field binding. Java field names use
 * camelCase while the JSON uses snake_case, so every non-matching field carries an
 * explicit {@link SerializedName}. Phase 4a instances are typically produced by
 * {@code gson.fromJson(reader, ManifestIndex.class)}.
 *
 * @see IndexProvider
 * @see RemoteJsonSource
 */
@Getter
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public final class ManifestIndex {

    /** The schema version, currently {@code 1} for {@code data/v1/}. */
    private final int version;

    /** ISO-8601 timestamp captured by the generator at emit time. */
    @SerializedName("generated_at")
    private final @NotNull String generatedAt;

    /** The {@code skyblock-data} commit sha at generation time, or {@code null} for local builds. */
    @SerializedName("commit_sha")
    private final @Nullable String commitSha;

    /** The distinct entity count (primaries only - {@code _extra} companions are folded into their primary's entry). */
    private final int count;

    /** The per-entity file entries, one per primary JSON file. */
    private final @NotNull ConcurrentList<Entry> files;

    /**
     * Single-file entry inside a {@link ManifestIndex}.
     *
     * <p>Describes one primary JSON file and, if {@link #hasExtra} is {@code true},
     * the companion {@code _extra} file that merges into the same table.
     */
    @Getter
    @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
    public static final class Entry {

        /** The primary file path relative to the {@code skyblock-data} repo root. */
        private final @NotNull String path;

        /** The category subdirectory the file lives in (e.g. {@code items}, {@code mobs}). */
        private final @NotNull String category;

        /** The {@code @Table(name = "...")} annotation value on the target entity. */
        @SerializedName("table_name")
        private final @NotNull String tableName;

        /** The fully-qualified Java class name of the target {@code JpaModel}. */
        @SerializedName("model_class")
        private final @NotNull String modelClass;

        /** The lowercase hex SHA-256 digest of the primary file's bytes. */
        @SerializedName("content_sha256")
        private final @NotNull String contentSha256;

        /** The primary file's byte length. */
        private final long bytes;

        /** {@code true} when an {@code _extra} companion file is present. */
        @SerializedName("has_extra")
        private final boolean hasExtra;

        /** The companion file path, or {@code null} when {@link #hasExtra} is {@code false}. */
        @SerializedName("extra_path")
        private final @Nullable String extraPath;

        /** The companion file's SHA-256, or {@code null} when {@link #hasExtra} is {@code false}. */
        @SerializedName("extra_sha256")
        private final @Nullable String extraSha256;

        /** The companion file's byte length, or {@code null} when {@link #hasExtra} is {@code false}. */
        @SerializedName("extra_bytes")
        private final @Nullable Long extraBytes;

    }

    /**
     * Returns an empty manifest. Intended for test stubs and defensive fallback paths
     * - not used by real consumers.
     *
     * @return an empty manifest with version {@code 1} and zero entries
     */
    public static @NotNull ManifestIndex empty() {
        return new ManifestIndex(1, "", null, 0, Concurrent.newUnmodifiableList());
    }

}
